version: "3.9"

services:
  frontend:
    image: glennclaes123/flowershop-frontend:latest
    container_name: flowershop_frontend
    restart: always
    networks:
      - flowershop_network

  nginx:
    image: nginx:latest
    container_name: flowershop_nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - frontend
    networks:
      - flowershop_network

networks:
  flowershop_network:
    driver: bridge