version: "3.9"

services:
  frontend:
    image: glennclaes123/flowershop-frontend:latest
    container_name: flowershop_frontend
    restart: always
    # Geen 'ports' hier, Traefik regelt de toegang via het 'web' netwerk
    labels:
      - "traefik.enable=true"
      # Tijdelijke toegang via IP/Host op poort 80
      - "traefik.http.routers.frontend.rule=PathPrefix(`/`)"
      - "traefik.http.routers.frontend.entrypoints=web"
      - "traefik.http.services.frontend.loadbalancer.server.port=80"
    networks:
      - web

  traefik:
    image: traefik:v3.0
    container_name: traefik
    restart: always
    environment:
      # Fix voor de "API version too old" error:
      - DOCKER_API_VERSION=1.24
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.myresolver.acme.email=jouw-email@example.com"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./letsencrypt:/letsencrypt"
    networks:
      - web

networks:
  web:
    driver: bridge